DEF USE_INTERRUPTS      EQU 1

DEF USE_AUDIO_ENGINE    EQU 1
DEF USE_INPUT_LIB       EQU 1
DEF USE_DETAILED_AUDIO  EQU 0
DEF USE_GAME_STATE      EQU 1
DEF USE_GAMELOOP        EQU 1
DEF USE_BOOTSTRAP       EQU 1
DEF TRACKTITLES_MAX_LENGTH EQU 16

DEF MUSIC_ASSETS_LOCATION EQU $1200

DEF USE_STAT_INTERRUPT      EQU 1
DEF USE_VBLANK_INTERRUPT    EQU 1

DEF DISPLAY_FLAGS = LCDCF_ON | LCDCF_BGON | LCDCF_WINON | LCDCF_BG8000 | LCDCF_WIN9C00