INCLUDE "macros/macros.inc"
DiatonicC::
DiatonicC_Bass::
        AU_CompactAdjustment %10, 13, 0, 4
        PianoNoteShort C3, 4
        PianoNoteShort D3, 4
        PianoNoteShort E3, 4
        PianoNoteShort F3, 4
        PianoNoteShort G3, 4
        PianoNoteShort A3, 4
        PianoNoteShort B3, 4
        PianoNoteShort C4, 4
    
DiatonicC_BassEnd::

DiatonicC_Treble::
    
        PianoNoteShort C5, 4
        PianoNoteShort B4, 4
        PianoNoteShort A4, 4
        PianoNoteShort G4, 4
        PianoNoteShort F4, 4
        PianoNoteShort E4, 4
        PianoNoteShort D4, 4
        PianoNoteShort C4, 4
    ;PianoRestShort 1
    AU_CompactAdjustment %00, 8, 0, 2
DiatonicC_TrebleEnd::
