IF !DEF(CONSTANTS_GBASM)
DEF CONSTANTS_GBASM EQU 0
;;; this defines a set of constants (load after assets are referenced)
;;; but before we do any init
;;; this must contain no code, just DEF and asserts
DEF TILES_LOCATION = _VRAM8000
DEF CHARS_LOCATION = _VRAM8800
DEF TILES_ROM_LOCATION = TilesROM
DEF TILEMAP_LOCATION = TILES_LOCATION + $0800


DEF TRACKTITLES_MAX_LENGTH = 16
;; layout: UI tiles, then Musical tiles, then the rest
DEF ASCII_TILES_SKIPLOAD = 16
DEF MUSICAL_TILES_SKIPEND = 16
ZoneLength UITiles, UI_TILES_SIZE, 0
ZoneLength MusicalTiles, MUSICAL_TILES_SIZE, MUSICAL_TILES_SKIPEND
ZoneLength SpritesROM, SPRITE_TILES_SIZE, 0
ZoneLength AsciiTiles, ASCII_TILES_SIZE, ASCII_TILES_SKIPLOAD
ZoneLength TrackerUI, TRACKER_UI_TILEMAP_SIZE, 0

DEF UI_TILES_COUNT = UI_TILES_SIZE / 16
DEF MUSICAL_TILES_COUNT = MUSICAL_TILES_SIZE / 16
DEF SPRITE_TILES_COUNT = SPRITE_TILES_SIZE / 16
DEF ASCII_TILES_COUNT = ASCII_TILES_SIZE / 16

DEF UI_TILES_OFFSET = 0 ; because it's the first thing we load
DEF MUSICAL_TILES_OFFSET = UI_TILES_OFFSET + UI_TILES_COUNT
DEF SPRITE_TILES_OFFSET = MUSICAL_TILES_OFFSET + MUSICAL_TILES_COUNT
DEF ASCII_TILES_OFFSET = 128


DEF LAST_TILE_OFFSET = MUSICAL_TILES_OFFSET + MUSICAL_TILES_COUNT

DEF GFX_TILES_OFFSET = UI_TILES_OFFSET

DEF STRING_TERMINATOR = $ff

PRINTLN "Tiles location: {TILES_LOCATION}; Tilemap location: {TILEMAP_LOCATION}"
PRINTLN "# of ui tiles: {UI_TILES_COUNT}, of musical tiles: {MUSICAL_TILES_COUNT}"
;;; Sanity checks
ASSERT LAST_TILE_OFFSET <= 255
ASSERT (TRACKER_UI_TILEMAP_SIZE) / 4 <= 255
ENDC