PROJECT_NAME = bare-template
include ../gameboy.mk

# $(BUILD_DIR)/obj/compact_audio.obj: $(BUILD_DIR)/obj/baseblocks/audio_engine.obj
# $(BUILD_DIR)/obj/tracker.obj: $(BUILD_DIR)/fw-obj/program.obj $(BUILD_DIR)/fw-obj/romstart.obj
